spring:
  application:
    name: service-B

server:
  port: 3333


eureka:
  client:
    serviceUrl:
#          defaultZone: http://10.44.145.103:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

