spring:
  application:
    name: zhiyin-gateway

# routes to serviceId
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
      path: /api-b/**
      serviceId: service-B
    zhiyin-ranker:
      path: /zhiyin-ranker/**
      serviceId: zhiyin-ranker

# routes to url
#zuul.routes.api-a-url.path=/api-a-url/**
#zuul.routes.api-a-url.url=http://localhost:2222/
#

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/zhiyin-eureka/eureka/
server:
  port: 8088