
spring:
  application:
    name: zhiyin-gateway

# routes to serviceId
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-A
    api-b:
      path: /api-b/**
      serviceId: service-B
    zhiyin-ranker:
      path: /zhiyin-ranker/**
      serviceId: zhiyin-ranker
    appapi:
      path: appapi/**
      serviceId: zhiyin-appapi-prod

eureka:
  client:
    serviceUrl:
#          defaultZone: http://10.44.145.103:8761/eureka/
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8888