
spring:
  application:
    name: admin-client
    version: 0.0.1

  boot:
    admin:
      url: http://101.200.185.137:10008
#      url: http://localhost:10008
      client:
        prefer-ip: false
#        service-url: http://${server.address}:${server.port}${server.contextPath}

server:
#  address: localhost
  contextPath: /${spring.application.name}
  port: 8085


info:
  version: 0.0.1
  info: ${spring.application.name}


