
spring:
  application:
    name: api-service
    version: 1.0.0

  boot:
    admin:
      url: http://101.200.185.137:10008
#      url: http://localhost:10008
      client:
        service-url: http://123.57.230.238:8084/api-service


server:
  contextPath: /api-service
  port: 8084



