server:
  contextPath: /notify-service
  port: 9001

spring:
  application:
    name: notification-service
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health

logging:
  file: target/boot-admin-sample.log