

spring:
  application:
    name: admin-server
  boot:
    admin:
      url: http://localhost:${server.port}
  cloud:
    config:
      enabled: false
    jackson:
      serialization:
        indent_output: true

server:
  port: 10008

endpoints:
  health:
    sensitive: false

management:
  port: 10009
  security:
    enabled: false

security:
  basic:
    enabled: true
  user:
    name: admin
    password: AdminBoot
  ignored: /api/**

info:
  version: 0.0.1
  stage: test

logging:
  file: log/boot-admin-sever.log
