

spring:
  application:
    name: springboot-admin-server
  boot:
    admin:
      url: http://localhost:${server.port}
  cloud:
    config:
      enabled: false
    jackson:
      serialization:
        indent_output: true

server:
  address: 101.200.185.137
  port: 10008

endpoints:
  health:
    sensitive: false

#that will not allow remote management connections
#management.port=8081
#management.address=127.0.0.1
management:
  port: 10009
  security:
    enabled: false

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin



info:
  version: 1.1
  stage: test

logging:
  file: target/boot-admin-sample.log
